### ISSUE TITLE
performance test and comparison with nodejs (expressjs)

### ISSUE THREAD

**Issue by tomassasovsky** [tomassasovsky/WeAppe.ar#16]

**Comment by NazarenoCavazzon** [comment]
We ran 2 tests on **Rust**, **Go Lang**, **Dart** and **JavaScript** using the [k6 open source tool](https://k6.io/) to measure performance. The base project was the same for the 4 languages, only one **Get** endpoint that retrieves a simple **JSON** message, {"name": "John Doe"},. To keep performance as good as possible in every case we disabled the logs of the server requests. For more info about the projects we're going to put the repos in the message below.

**First Test** (To break the server): 

- from 0 VUs (Virtual Users) to 20,000 in 5min
- from 20,000 VUs to 0 in 2m

**Second Test** (To stress the server):

- from 0 VUs to 5,000 in 3m and holding it for 2m
- from 5,000 VUs to 10,000 in 3m and holding it for 2m
- from 10,000 VUs to 0 in 1m

**RESULTS**

**JS**:
First Test (it broke at 11,000 VUs approx.):
![image](https://user-images.githubusercontent.com/49735945/164955448-44b52d9f-ebb7-4c84-8ef7-961e20c04779.png)

Second Test:
![image](https://user-images.githubusercontent.com/49735945/164955458-872d63e6-01d0-47c6-80ec-73378880baf7.png)


**Dart**:
First Test (it broke at 13,000 VUs approx.):
![image](https://user-images.githubusercontent.com/49735945/164955478-f031f3cc-7f11-4fa8-b655-0844a701f47b.png)

Second Test:
![image](https://user-images.githubusercontent.com/49735945/164955485-92a0df8b-3acc-4b35-b3fb-178f869040cb.png)


**Go**:
First Test (it broke at 16,000 VUs approx.):
![image](https://user-images.githubusercontent.com/49735945/164955769-ff47c738-cd41-4b91-acde-ddda8b6fa4c4.png)

Second Test:
![image](https://user-images.githubusercontent.com/49735945/164955551-3ed0773b-f84a-46c2-8b82-78e257639d10.png)


**Rust**
First Test (it broke at 17,000 VUs approx.)::
![image](https://user-images.githubusercontent.com/49735945/164956400-bf02251c-353f-447f-b5ce-bec2e7f9b9f5.png)

Second Test:
![image](https://user-images.githubusercontent.com/49735945/164956760-03fdeae1-f741-479c-b70c-a7ad2469b461.png)

**CONCLUSIONS**
**Dart** seems to be more closer to **Go** and **Rust** than to **JS** in our rudimentary performance tests, but something to keep in account is that Dart Backend is still very raw and it's in an early stage, so there is a lot of development to be done, and something that we noticed is that **Dart** may lack of scalability when speaking about micro services, that's because we don't currently have an approach to solve this problem.
